import express,{Application} from "express"
import morgan from "morgan";
import helmet from "helmet";
import cookieParser from "cookie-parser";
import organizationRoutes from "@routes/organization.route.js";
import sessionRoutes from "@routes/session.route.js";
import bulkRoutes from "@routes/bulk.route.js";
import errorHandler from "@middleware/errorHandler.js";
import { setupSwagger } from "@config/swagger.js";
import "./config/tracing.js";
import healthRoutes from "@routes/health.route.js"; // [NEW]
import { metricsMiddleware } from "@middleware/metricsMiddleware.js"; // [NEW]
import { tracingMiddleware } from "@middleware/tracingMiddleware.js"; // [NEW]
import { register } from "@config/metrics.js"; // [NEW]
import { logger } from "./config/logger.js";

const app:Application = express();

app.use(express.json());
app.use(express.urlencoded({extended:true}));
app.use(cookieParser());
app.use(tracingMiddleware);
app.use(metricsMiddleware);
const morganFormat = process.env.NODE_ENV === "production" ? "combined" : "dev";

app.use(
  morgan(morganFormat, {
    stream: {
      write: (message) => {
        // .trim() removes the extra newline generated by morgan
        logger.info(message.trim());
      },
    },
  })
);

// CORS for Swagger UI
app.use((req, res, next) => {
  res.header('Access-Control-Allow-Origin', '*');
  res.header('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, PATCH, OPTIONS');
  res.header('Access-Control-Allow-Headers', 'Origin, X-Requested-With, Content-Type, Accept, Authorization');
  if (req.method === 'OPTIONS') {
    return res.sendStatus(200);
  }
  next();
});

app.use(
  helmet({
    ...(process.env.NODE_ENV === "production" 
      ? {} 
      : {
          contentSecurityPolicy: {
            directives: {
              defaultSrc: ["'self'"],
              styleSrc: ["'self'", "'unsafe-inline'"],
              scriptSrc: ["'self'", "'unsafe-inline'", "'unsafe-eval'"],
              imgSrc: ["'self'", "data:", "https:"],
              connectSrc: ["'self'", "http://localhost:8000", "http://localhost:4001"],
              fontSrc: ["'self'", "data:"],
            },
          },
          crossOriginEmbedderPolicy: false,
          crossOriginOpenerPolicy: false,
          crossOriginResourcePolicy: { policy: "cross-origin" },
        }
    ),
  })
);

//routes
app.get("/",(req,res)=>{
    res.status(200).json({message:"Auth Service is up and running"});
})

// Setup Swagger BEFORE other routes
if (process.env.NODE_ENV !== 'production') {
    setupSwagger(app);
}

app.get("/auth/api/metrics", async (req, res) => {
  res.setHeader('Content-Type', register.contentType);
  res.send(await register.metrics());
});

//All routes
app.use("/auth/api", healthRoutes);
app.use("/auth/api",organizationRoutes)
app.use("/auth/api",sessionRoutes)
app.use("/auth/api/bulk",bulkRoutes)

//health check
app.get("/auth/api/health",(req,res)=>{
    res.status(200).json({status:"ok"});
})



// Error handling middleware must be last
app.use(errorHandler);

export default app;